# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_exam_1/image.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import paho.mqtt.client as mqtt
import json
import time
import threading
import sys
import urllib.request
import tempfile


class Ui_MainWindow(object):
    broker = 'mqtt.eclipseprojects.io'
    client = mqtt.Client("gui_ruiz")
    client.connect(broker)

    updateImageSignal = QtCore.pyqtSignal(list)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.frame)

        self.imageLabel = QtWidgets.QLabel(self.frame)
        self.imageLabel.setGeometry(QtCore.QRect(0, 0, self.frame.width(), self.frame.height()))
        self.imageLabel.setScaledContents(True)

        self.frameLayout.addWidget(self.imageLabel)
        self.frame.setLayout(self.frameLayout)

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #connect to broker and subscribe to parking_ruiz and temperature_ruiz topics
        self.client.connect(self.broker)
        self.client.loop_start()
        self.client.subscribe("image_ruiz")
        self.client.on_message = self.on_message

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def on_message(self, client, userdata, message):
        try: 
            payload = message.payload.decode('utf-8')
            print(f"[{type}] Received message: {str(payload)}")
        except Exception as e:
            print(f"Error processing message: {e}")

    def displayImageUrl(self, imageUrl):
        try:
            with urllib.request.urlopen(imageUrl) as url:
                data = url.read()
                pixmap = QtGui.QPixmap()
                pixmap.loadFromData(data)

                scaledPixmap = pixmap.scaled(self.imageLabel.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
                
                self.imageLabel.setPixmap(scaledPixmap)
                self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)

        except Exception as e:
            print(f"Error handling image: {e}")


class MyApplication(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MyApplication()
    mainWindow.show()
    sys.exit(app.exec_())