# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import threading
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import paho.mqtt.client as mqtt
import json


class Ui_MainWindow(object):
    broker = 'broker.hivemq.com'
    client = mqtt.Client("gui_ruiz")
    spots = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 280, 951, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageboardLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.messageboardLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageboardLabel.setObjectName("messageboardLabel")
        self.verticalLayout.addWidget(self.messageboardLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.messageBoardInput = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.messageBoardInput.setObjectName("messageBoardInput")
        self.horizontalLayout_4.addWidget(self.messageBoardInput)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.messageBoardSend = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageBoardSend.sizePolicy().hasHeightForWidth())
        self.messageBoardSend.setSizePolicy(sizePolicy)
        self.messageBoardSend.setObjectName("messageBoardSend")
        self.messageBoardSend.clicked.connect(self.sendBoardMessage)
        self.horizontalLayout_6.addWidget(self.messageBoardSend)
        spacerItem3 = QtWidgets.QSpacerItem(58, 17, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 941, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.parking1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking1.sizePolicy().hasHeightForWidth())
        self.parking1.setSizePolicy(sizePolicy)
        self.parking1.setStyleSheet("background-color: red;\n"
"border: 1px solid black;\n"
"")
        self.parking1.setAlignment(QtCore.Qt.AlignCenter)
        self.parking1.setObjectName("parking1")
        self.horizontalLayout.addWidget(self.parking1)
        self.parking2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking2.sizePolicy().hasHeightForWidth())
        self.parking2.setSizePolicy(sizePolicy)
        self.parking2.setStyleSheet("background-color: red;\n"
"border: 1px solid black;\n"
"")
        self.parking2.setAlignment(QtCore.Qt.AlignCenter)
        self.parking2.setObjectName("parking2")
        self.horizontalLayout.addWidget(self.parking2)
        self.parking3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking3.sizePolicy().hasHeightForWidth())
        self.parking3.setSizePolicy(sizePolicy)
        self.parking3.setStyleSheet("background-color: red;\n"
"border: 1px solid black;\n"
"")
        self.parking3.setAlignment(QtCore.Qt.AlignCenter)
        self.parking3.setObjectName("parking3")
        self.horizontalLayout.addWidget(self.parking3)
        self.parking4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking4.sizePolicy().hasHeightForWidth())
        self.parking4.setSizePolicy(sizePolicy)
        self.parking4.setStyleSheet("background-color: red;\n"
"border: 1px solid black;\n"
"")
        self.parking4.setAlignment(QtCore.Qt.AlignCenter)
        self.parking4.setObjectName("parking4")
        self.horizontalLayout.addWidget(self.parking4)
        self.parking5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking5.sizePolicy().hasHeightForWidth())
        self.parking5.setSizePolicy(sizePolicy)
        self.parking5.setStyleSheet("background-color: red;\n"
"border: 1px solid black;\n"
"")
        self.parking5.setAlignment(QtCore.Qt.AlignCenter)
        self.parking5.setObjectName("parking5")
        self.horizontalLayout.addWidget(self.parking5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tempSensorLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.tempSensorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempSensorLabel.setObjectName("tempSensorLabel")
        self.verticalLayout_3.addWidget(self.tempSensorLabel)
        self.tempSensorValueLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.tempSensorValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempSensorValueLabel.setObjectName("tempSensorValueLabel")
        self.verticalLayout_3.addWidget(self.tempSensorValueLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.emergencyOffButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergencyOffButton.sizePolicy().hasHeightForWidth())
        self.emergencyOffButton.setSizePolicy(sizePolicy)
        self.emergencyOffButton.setStyleSheet("background-color: red;\n"
"border-radius: 50%;\n"
"border: 1px solid black;\n"
"line-height: 50px;\n"
"width: 50px;\n"
"height: 50px;")
        self.emergencyOffButton.setObjectName("emergencyOffButton")
        self.horizontalLayout_3.addWidget(self.emergencyOffButton)
        self.emergencyOffLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.emergencyOffLabel.setObjectName("emergencyOffLabel")
        self.horizontalLayout_3.addWidget(self.emergencyOffLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.emergencyOnButton = emergencyLightGraphic()
        self.emergencyOnButton.setObjectName("emergencyOnButton")
        self.horizontalLayout_5.addWidget(self.emergencyOnButton)
        self.emergencyOnLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.emergencyOnLabel.setObjectName("emergencyOnLabel")
        self.horizontalLayout_5.addWidget(self.emergencyOnLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.client.connect(self.broker)
        self.client.loop_start()
        self.client.subscribe("parking_ruiz")
        self.client.on_message = self.on_message

        self.spots.extend([self.parking1, self.parking2, self.parking3, self.parking4, self.parking5])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.messageboardLabel.setText(_translate("MainWindow", "Display message to display board"))
        self.messageBoardInput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.messageBoardInput.setPlaceholderText(_translate("MainWindow", "Type message here"))
        self.messageBoardSend.setText(_translate("MainWindow", "Display"))
        self.parking1.setText(_translate("MainWindow", "1"))
        self.parking2.setText(_translate("MainWindow", "2"))
        self.parking3.setText(_translate("MainWindow", "3"))
        self.parking4.setText(_translate("MainWindow", "4"))
        self.parking5.setText(_translate("MainWindow", "5"))
        self.tempSensorLabel.setText(_translate("MainWindow", "Parking Lot Temperature Sensor"))
        self.tempSensorValueLabel.setText(_translate("MainWindow", "Placeholder"))
        self.emergencyOffButton.setText(_translate("MainWindow", "PushButton"))
        self.emergencyOffLabel.setText(_translate("MainWindow", "Turn Emergency Light Off"))
        self.emergencyOnLabel.setText(_translate("MainWindow", "Turn Emergency Light On"))

    def sendBoardMessage(self):
        try:
            self.client.connect(self.broker)
            raw = {
                "type":"msg_board",
                "data":self.messageBoardInput.toPlainText()
			}
            payload = json.dumps(raw)
            self.client.publish("MSG_BOARD", payload)
            print("[MSG BOARD] Just published %s to topic \"MSG_BOARD\"" % payload)
        except Exception as e:
             print(f'[MSG BOARD] {e}') 

    def updateParking(self, parking):
        for i in range(0, len(parking)):
            if parking[i] == True:
                self.spots[i].setStyleSheet("background-color: red;\n"
"border: 1px solid black;\n"
"")
            else:
                self.spots[i].setStyleSheet("background-color: green;\n"
"border: 1px solid black;\n"
"")
                
    def on_message(self, client, userdata, message):
        payload = json.loads(message.payload)
        type = payload["type"]
        data = payload["data"]
        if type == "parking":
            print(f"[{type}] Received message: {str(data)}")
            self.updateParking(data)



class emergencyLightGraphic(QtWidgets.QWidget):
    def paintEvent(self, event):
        painter = QtGui.QPainter(self)
        painter.setBrush(QtGui.QBrush(QtCore.Qt.red))
        painter.drawEllipse(160,0,50, 50)



class MyApplication(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MyApplication()
    mainWindow.show()
    sys.exit(app.exec_())